package bangla.grammarchecker;

import java.util.ArrayList;
import java.util.List;

public class CreateShadhuVerbForm1 {
	
	public static List<String> createVerb(String root) {
		List<String> ret = new ArrayList<>();
		ret.add(root+"ইতেছিলাম");
		ret.add(root+"ইতেছিলামই");
		ret.add(root+"ইতেছিলামও");
		ret.add(root+"ইতেছিল");
		ret.add(root+"ইতেছিলই");
		ret.add(root+"ইতেছিলও");
		ret.add(root+"ইলে");
		ret.add(root+"ইলেই");
		ret.add(root+"ইলেও");
		ret.add(root+"ইয়াছেন");
		ret.add(root+"ইয়াছেনই");
		ret.add(root+"ইয়েছেনই");
		ret.add(root+"ইবে");
		ret.add(root+"ইবেই");
		ret.add(root+"ইবেই");
		ret.add(root+"ইল");
		ret.add(root+"ইলই");
		ret.add(root+"ইলও");
		ret.add(root+"ইয়া");
		ret.add(root+"ইয়াই");
		ret.add(root+"ইয়াও");
		ret.add(root+"ইবি");
		ret.add(root+"ইবিই");
		ret.add(root+"ইবিও");
		ret.add(root+"ইবে");
		ret.add(root+"ইবেই");
		ret.add(root+"ইবেও");
		ret.add(root+"ইবে");
		ret.add(root+"ইবেই");
		ret.add(root+"ইবেও");
		ret.add(root+"ইয়াছে");
		ret.add(root+"ইয়াছেই");
		ret.add(root+"ইয়াছেও");
		ret.add(root+"ইবি");
		ret.add(root+"ইবিই");
		ret.add(root+"ইবিও");
		ret.add(root+"ইলি");
		ret.add(root+"ইলিই");
		ret.add(root+"ইলিও");
		ret.add(root+"ইতেছে");
		ret.add(root+"ইতেছেই");
		ret.add(root+"ইতেছেও");
		ret.add(root+"ন");
		ret.add(root+"নই");
		ret.add(root+"নও");
		ret.add(root+"ইতে থাকিব");
		ret.add(root+"ইতে থাকিবই");
		ret.add(root+"ইতে থাকিবও");
		ret.add(root+"ইয়াছিল");
		ret.add(root+"ইয়াছিলই");
		ret.add(root+"ইয়াছিলও");
		ret.add(root+"ইবেন");
		ret.add(root+"ইবেনই");
		ret.add(root+"ইবেনও");
		ret.add(root+"ইতেছিল");
		ret.add(root+"ইতেছিলই");
		ret.add(root+"ইতেছিলও");
		ret.add(root+"ইব");
		ret.add(root+"ইবই");
		ret.add(root+"ইবও");
		ret.add(root+"ইয়াছিল");
		ret.add(root+"ইয়াছিলই");
		ret.add(root+"ইয়াছিলও");
		ret.add(root+"ইতে");
		ret.add(root+"ইতেই");
		ret.add(root+"ইতেও");
		ret.add(root+"ইয়াছিলাম");
		ret.add(root+"ইয়াছিলামই");
		ret.add(root+"ইয়াছিলামও");
		ret.add(root+"ন");
		ret.add(root+"নই");
		ret.add(root+"নও");
		ret.add(root+"ইলে");
		ret.add(root+"ইলেই");
		ret.add(root+"ইলেও");
		ret.add(root+"ইতে থাকিবেন");
		ret.add(root+"ইতে থাকিবেনই");
		ret.add(root+"ইতে থাকিবেনও");
		ret.add(root+"ইস");
		ret.add(root+"ইসই");
		ret.add(root+"ইসও");
		ret.add(root+"ই");
		ret.add(root+"ইই");
		ret.add(root+"ইও");
		ret.add(root+"ইতেছি");
		ret.add(root+"ইতেছিই");
		ret.add(root+"ইতেছিও");
		ret.add(root+"ইতেছিলি");
		ret.add(root+"ইতেছিলিই");
		ret.add(root+"ইতেছলিও");
		ret.add(root+"ইলেন");
		ret.add(root+"ইলেনই");
		ret.add(root+"ইলেনও");
		ret.add(root+"ইবে");
		ret.add(root+"ইবেই");
		ret.add(root+"ইবেও");
		ret.add(root+"নো");
		ret.add(root+"নোই");
		ret.add(root+"নোও");
		ret.add(root+"ইতেন");
		ret.add(root+"ইতেনই");
		ret.add(root+"ইতেনও");
		ret.add(root+"স");
		ret.add(root+"সই");
		ret.add(root+"সও");
		ret.add(root+"ইবে");
		ret.add(root+"ইবেই");
		ret.add(root+"ইবেও");
		ret.add(root+"ইত");
		ret.add(root+"ইতই");
		ret.add(root+"ইতও");
		ret.add(root+"ইতে থাকিবে");
		ret.add(root+"ইতে থাকিবেই");
		ret.add(root+"ইতে থাকিবেও");
		ret.add(root+"ইতেছিস");
		ret.add(root+"ইতেছিসই");
		ret.add(root+"ইতেছিসও");
		ret.add(root+"ও");
		ret.add(root+"ওই");
		ret.add(root+"ওও");
		ret.add(root+"ইয়াছিলেন");
		ret.add(root+"ইয়াছিলেনই");
		ret.add(root+"ইয়াছিলেনও");
		ret.add(root+"ইতেছিলে");
		ret.add(root+"ইচতেছিলেই");
		ret.add(root+"ইতেছিলেও");
		ret.add(root+"ইতেছ");
		ret.add(root+"ইতেছই");
		ret.add(root+"ইতেছও");
		ret.add(root+"ইতে থাকিবেন");
		ret.add(root+"ইতে থাকিবেনই");
		ret.add(root+"ইতে থাকিবেনও");
		ret.add(root+"ইয়াছিস");
		ret.add(root+"ইয়াছিসই");
		ret.add(root+"ইয়াছিসও");
		ret.add(root+"উক");
		ret.add(root+"উকই");
		ret.add(root+"উকও");
		ret.add(root+"ইয়াছেন");
		ret.add(root+"ইয়াছেনই");
		ret.add(root+"ইয়াছেনও");
		ret.add(root+"ইবেন");
		ret.add(root+"ইবেনই");
		ret.add(root+"ইবেনও");
		ret.add(root+"ইবি");
		ret.add(root+"ইবিই");
		ret.add(root+"ইবিও");
		ret.add(root+"ইবেন");
		ret.add(root+"ইবেনই");
		ret.add(root+"ইবেনও");
		ret.add(root+"ইয়াছিলেন");
		ret.add(root+"ইয়াছিলেনই");
		ret.add(root+"ইয়াছেলেনও");
		ret.add(root+"য়");
		ret.add(root+"য়ই");
		ret.add(root+"য়ও");
		ret.add(root+"ইতেছে");
		ret.add(root+"ইতেছেই");
		ret.add(root+"ইতেছেও");
		ret.add(root+"ইলাম");
		ret.add(root+"ইলামই");
		ret.add(root+"ইলামও");
		ret.add(root+"ও");
		ret.add(root+"ওই");
		ret.add(root+"ওও");
		ret.add(root+"ইয়াছে");
		ret.add(root+"ইয়াছেই");
		ret.add(root+"ইয়াছেও");
		ret.add(root+"ইতে থাকিবে");
		ret.add(root+"ইতে থাকিবেই");
		ret.add(root+"ইতে থাকিবেও");
		ret.add(root+"ইতে থাকিবি");
		ret.add(root+"ইতে থাকিবিই");
		ret.add(root+"ইতে থাকিবিও");
		ret.add(root+"উক");
		ret.add(root+"উকই");
		ret.add(root+"উকও");
		ret.add(root+"ইয়াছি");
		ret.add(root+"ইয়াছিই");
		ret.add(root+"ইয়াছিও");
		ret.add(root+"ইতি");
		ret.add(root+"ইতিই");
		ret.add(root+"ইতিও");
		ret.add(root+"ইবার");
		ret.add(root+"ইবারই");
		ret.add(root+"ইবারও");
		ret.add(root+"ইতে থাকিবে");
		ret.add(root+"ইতে থাকিবেই");
		ret.add(root+"ইতে থাকিবেও");
		ret.add(root+"ইতে");
		ret.add(root+"ইতেই");
		ret.add(root+"ইতেও");
		ret.add(root+"ইতেন");
		ret.add(root+"ইতেনই");
		ret.add(root+"ইতেনও");
		ret.add(root+"ইতেছিলেন");
		ret.add(root+"ইতেছিলেনই");
		ret.add(root+"চ্ছিলেনও");
		ret.add(root+"ইতেছেন");
		ret.add(root+"ইতেছেনই");
		ret.add(root+"ইতেছেনও");
		ret.add(root+"ইবি");
		ret.add(root+"ইবিই");
		ret.add(root+"ইবিও");
		ret.add(root+"ন");
		ret.add(root+"নই");
		ret.add(root+"নও");
		ret.add(root+"ইয়াছ");
		ret.add(root+"ইয়াছই");
		ret.add(root+"য়াছও");
		ret.add(root+"ইলেন");
		ret.add(root+"ইলেনই");
		ret.add(root+"ইলেনও");
		ret.add(root+"ইয়াছিলি");
		ret.add(root+"ইয়াছিলিই");
		ret.add(root+"য়েছিলিও");
		ret.add(root+"ইতেছিলেন");
		ret.add(root+"ইতেছিলেনই");
		ret.add(root+"ইতেছিলেনও");
		ret.add(root+"ইতেছেন");
		ret.add(root+"ইতেছেনই");
		ret.add(root+"ইতেছেনও");
		ret.add(root+"ইত");
		ret.add(root+"ইতই");
		ret.add(root+"ইতও");
		ret.add(root+"ইতাম");
		ret.add(root+"ইতামই");
		ret.add(root+"ইতামও");
		ret.add(root+"ইল");
		ret.add(root+"ইলই");
		ret.add(root+"ইলও");
		ret.add(root+"য়");
		ret.add(root+"য়ই");
		ret.add(root+"য়ও");
		ret.add(root+"ইয়াছিলে");
		ret.add(root+"ইয়াছিলেই");
		ret.add(root+"ইয়াছিলেও");
		ret.add(root+"ন");
		ret.add(root+"নই");
		ret.add(root+"নও");
		return ret;
	}

}
