package bangla.grammarchecker;

import java.util.ArrayList;
import java.util.List;

public class CreateShadhuVerbForm2 {
	
	public static List<String> createVerb(String root) {
		List<String> ret = new ArrayList<>();
		ret.add(root+"য়াছিলাম");
		ret.add(root+"য়াছিলামই");
		ret.add(root+"তেছিলামও");
		ret.add(root+"তেছিল");
		ret.add(root+"তেছিলই");
		ret.add(root+"তেছিলও");
		ret.add(root+"য়া");
		ret.add(root+"য়াই");
		ret.add(root+"য়াও");
		ret.add(root+"য়াছেন");
		ret.add(root+"য়াছেনই");
		ret.add(root+"য়াছেনও");
		ret.add(root+"বে");
		ret.add(root+"বেই");
		ret.add(root+"বেও");
		ret.add(root+"ল");
		ret.add(root+"লই");
		ret.add(root+"লও");
		ret.add(root+"য়াছিল");
		ret.add(root+"য়াছিলই");
		ret.add(root+"য়াছিলও");
		ret.add(root+"বেন");
		ret.add(root+"বেনই");
		ret.add(root+"বেনও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"য়াছে");
		ret.add(root+"য়াছেই");
		ret.add(root+"য়াছেও");
		ret.add(root+"বেও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"লি");
		ret.add(root+"লিই");
		ret.add(root+"লিও");
		ret.add(root+"য়াছ");
		ret.add(root+"তেছেই");
		ret.add(root+"তেছেও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"তে থাকিব");
		ret.add(root+"তে থাকিবই");
		ret.add(root+"তে থাকিবও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"য়াছিলই");
		ret.add(root+"বেনও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"ব");
		ret.add(root+"বই");
		ret.add(root+"বও");
		ret.add(root+"য়াছিল");
		ret.add(root+"য়াছিলই");
		ret.add(root+"য়াছিলও");
		ret.add(root+"তে");
		ret.add(root+"তেই");
		ret.add(root+"তেও");
		ret.add(root+"য়াছিলাম");
		ret.add(root+"য়াছিলামই");
		ret.add(root+"য়াছিলামও");
		ret.add(root+"লে");
		ret.add(root+"লেই");
		ret.add(root+"লেও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"তে থাকিবেন");
		ret.add(root+"তে থাকিবেনই");
		ret.add(root+"তে থাকিবেনও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"তেছি");
		ret.add(root+"তেছিই");
		ret.add(root+"তেছিও");
		ret.add(root+"তেছিলি");
		ret.add(root+"তেছিলিই");
		ret.add(root+"তেছিলিও");
		ret.add(root+"লেন");
		ret.add(root+"লেনই");
		ret.add(root+"লেনও");
		ret.add(root+"বে");
		ret.add(root+"বেই");
		ret.add(root+"বেও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"তেন");
		ret.add(root+"তেনই");
		ret.add(root+"তেনও");
		ret.add(root+"ত");
		ret.add(root+"তই");
		ret.add(root+"তও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"তে থাকিবে");
		ret.add(root+"তে থাকিবেই");
		ret.add(root+"তে থাকিবেও");
		ret.add(root+"তেছিস");
		ret.add(root+"তেছিসই");
		ret.add(root+"তেছিসও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"তেছিলেন");
		ret.add(root+"তেছিলেনই");
		ret.add(root+"তেছিলেনও");
		ret.add(root+"তেছিলে");
		ret.add(root+"তেছিলেই");
		ret.add(root+"তেছিলও");
		ret.add(root+"তেছ");
		ret.add(root+"তেছই");
		ret.add(root+"তেছও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"য়াছিস");
		ret.add(root+"য়াছিসই");
		ret.add(root+"য়াছিসও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"য়াছেন");
		ret.add(root+"য়াছেনই");
		ret.add(root+"য়াছেনও");
		ret.add(root+"বেন");
		ret.add(root+"বেনই");
		ret.add(root+"বেনও");
		ret.add(root+"বি");
		ret.add(root+"বিই");
		ret.add(root+"বিও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"য়া");
		ret.add(root+"য়াই");
		ret.add(root+"য়াও");
		ret.add(root+"য়াছে");
		ret.add(root+"য়াছেই");
		ret.add(root+"য়াছেও");
		ret.add(root+"লাম");
		ret.add(root+"লামই");
		ret.add(root+"লামও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"য়াছে");
		ret.add(root+"য়াছেই");
		ret.add(root+"য়াছেও");
		ret.add(root+"তে থাকিবি");
		ret.add(root+"তে থাকিবিই");
		ret.add(root+"তে থাকিবিও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"য়াছি");
		ret.add(root+"য়াছিই");
		ret.add(root+"য়াছিও");
		ret.add(root+"তি");
		ret.add(root+"তিই");
		ret.add(root+"তিও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"তেছিলেন");
		ret.add(root+"তেছিলেনই");
		ret.add(root+"তেছিলেনও");
		ret.add(root+"তেছেন");
		ret.add(root+"তেছেনই");
		ret.add(root+"তেছেনও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"য়াছ");
		ret.add(root+"য়াছই");
		ret.add(root+"য়াছও");
		ret.add(root+"য়াছিলি");
		ret.add(root+"য়াছিলিই");
		ret.add(root+"য়াছিলিও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"তাম");
		ret.add(root+"তামই");
		ret.add(root+"তামও");
		ret.add(root+"ল");
		ret.add(root+"লই");
		ret.add(root+"লও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");
		ret.add(root+"য়াছিলে");
		ret.add(root+"য়াছিলেই");
		ret.add(root+"য়াছিলেও");
		ret.add("invalid");
		ret.add("invalid");
		ret.add("invalid");

		
		return ret;
	}

}
