package bangla.grammarchecker;

public enum GrammerCheckerTypes {
	
	SHADHU_CHOLIT_ERROR,
	SPACE_BETWEEN_WORDS_ERROR,
	NO_SPACE_BETWEEN_WORDS_ERROR,
	SUBJECT_VERB_AGREEMENT_ERROR,
	WRONG_NIRDESHOK_ERROR,
	NEGATIVE_TYPE_WORD_ERROR

}
